/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingOrderIdRouteImport } from './routes/tracking.$orderId'
import { Route as CatalogStoreRouteImport } from './routes/catalog.$store'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingOrderIdRoute = TrackingOrderIdRouteImport.update({
  id: '/tracking/$orderId',
  path: '/tracking/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogStoreRoute = CatalogStoreRouteImport.update({
  id: '/catalog/$store',
  path: '/catalog/$store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/credits': typeof CreditsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/catalog/$store': typeof CatalogStoreRoute
  '/tracking/$orderId': typeof TrackingOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/credits': typeof CreditsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/catalog/$store': typeof CatalogStoreRoute
  '/tracking/$orderId': typeof TrackingOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/credits': typeof CreditsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/catalog/$store': typeof CatalogStoreRoute
  '/tracking/$orderId': typeof TrackingOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/credits'
    | '/orders'
    | '/profile'
    | '/catalog/$store'
    | '/tracking/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/credits'
    | '/orders'
    | '/profile'
    | '/catalog/$store'
    | '/tracking/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/credits'
    | '/orders'
    | '/profile'
    | '/catalog/$store'
    | '/tracking/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CreditsRoute: typeof CreditsRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  CatalogStoreRoute: typeof CatalogStoreRoute
  TrackingOrderIdRoute: typeof TrackingOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$orderId': {
      id: '/tracking/$orderId'
      path: '/tracking/$orderId'
      fullPath: '/tracking/$orderId'
      preLoaderRoute: typeof TrackingOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$store': {
      id: '/catalog/$store'
      path: '/catalog/$store'
      fullPath: '/catalog/$store'
      preLoaderRoute: typeof CatalogStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CreditsRoute: CreditsRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  CatalogStoreRoute: CatalogStoreRoute,
  TrackingOrderIdRoute: TrackingOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
